version: '3.8'

services:
  moneyforward-collector:
    build:
      context: ./
    volumes:
      - type: bind
        source: ./data
        target: /data
      - type: bind
        source: ./config.json
        target: /app/config.json
