name: Docker Image CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ github.event.repository.name }}:$(date +%s)

      - name: Build by Docker Compose
        run: |
          touch moneyforward-collector.env
          docker-compose build
